declare const mermaid: any;

export type Edge = [string, string];

// mermaid.initialize({ startOnLoad: false });
// mermaid.initialize({ startOnLoad: false, suppressErrorRendering: true, maxTextSize: 1000000 });
export const darkModeToggle = document.getElementById('darkModeToggle') as HTMLInputElement;
export const mermaidOptions = () => ({ startOnLoad: false, suppressErrorRendering: true, maxTextSize: 1000000, theme: darkModeToggle.checked ? 'dark' : 'default', themeVariables: darkModeToggle.checked ? { primaryColor: '#ececff', nodeBkg: '#ececff', mainBkg: '#ececff', primaryTextColor: '#000', nodeTextColor: '#000', primaryBorderColor: '#9370db', nodeBorder: '#9370db' } : {} });
mermaid.initialize(mermaidOptions());
export const codeBox = document.getElementById('code') as HTMLTextAreaElement;
export const diagramBox = document.getElementById('diagram')!;
export const errorBox = document.getElementById('error')!;
export const errorLog = document.getElementById('errorLog')!;
export const statusBox = document.getElementById('status')!;
export const selectBox = document.getElementById('diagramSelect') as HTMLSelectElement;
export const currentFileName = document.getElementById('currentFileName')!;
export const drawer = document.getElementById('drawer')!;
export const drawerToggle = document.getElementById('drawerToggle')!;
export const openFileBtn = document.getElementById('openFileBtn')!;
export const openFileInput = document.getElementById('openFileInput') as HTMLInputElement;
export const mainBox = document.getElementById('main')!;
export const outputBox = document.getElementById('output')!;
export const phoneDiagramBox = document.getElementById('phoneDiagram')!;
export const previousDecisionBtn = document.getElementById('previousDecisionBtn')!;
export const nextDecisionBtn = document.getElementById('nextDecisionBtn')!;
export const decisionCounter = document.getElementById('decisionCounter')!;
export const zoomInBtn = document.getElementById('zoomInBtn') as HTMLButtonElement;
export const zoomOutBtn = document.getElementById('zoomOutBtn') as HTMLButtonElement;
export const zoomResetBtn = document.getElementById('zoomResetBtn') as HTMLButtonElement;
export const zoomLevel = document.getElementById('zoomLevel')!;
export const functionsOnlyToggle = document.getElementById('functionsOnlyToggle') as HTMLInputElement;
export const nodeActions = document.getElementById('nodeActions')!;
export const selectedNodeBox = document.getElementById('selectedNode')!;
export const nodeInspector = document.getElementById('nodeInspector')!;
export const nodeInspectorTitle = document.getElementById('nodeInspectorTitle')!;
export const nodeTextInput = document.getElementById('nodeTextInput') as HTMLInputElement;
// Retired: replaced by the Class picker below (see class-defs.ts).
// export const nodeTypeRow = document.getElementById('nodeTypeRow')!;
// export const nodeTypeInput = document.getElementById('nodeTypeInput') as HTMLInputElement;
// export const nodeTypeColorRow = document.getElementById('nodeTypeColorRow')!;
// export const nodeTypeColorInput = document.getElementById('nodeTypeColorInput') as HTMLInputElement;
export const nodeClassRow = document.getElementById('nodeClassRow')!;
export const classPickerBtn = document.getElementById('classPickerBtn') as HTMLButtonElement;
export const classPickerSwatch = document.getElementById('classPickerSwatch')!;
export const classPickerLabel = document.getElementById('classPickerLabel')!;
export const classPickerList = document.getElementById('classPickerList')!;
export const classEditorDialog = document.getElementById('classEditorDialog') as HTMLDialogElement;
export const classEditorName = document.getElementById('classEditorName') as HTMLInputElement;
export const classEditorFill = document.getElementById('classEditorFill') as HTMLInputElement;
export const classEditorStroke = document.getElementById('classEditorStroke') as HTMLInputElement;
export const classEditorError = document.getElementById('classEditorError')!;
export const classEditorCancelBtn = document.getElementById('classEditorCancelBtn')!;
export const classEditorCreateBtn = document.getElementById('classEditorCreateBtn')!;
export const classesMenuBtn = document.getElementById('classesMenuBtn')!;
export const classesDialog = document.getElementById('classesDialog') as HTMLDialogElement;
export const classesList = document.getElementById('classesList')!;
export const classesError = document.getElementById('classesError')!;
export const classesNewBtn = document.getElementById('classesNewBtn')!;
export const classesCloseBtn = document.getElementById('classesCloseBtn')!;
export const nodeInspectorDismissBtn = document.getElementById('nodeInspectorDismissBtn')!;
export const destinationRow = document.getElementById('destinationRow')!;
export const destinationSelect = document.getElementById('destinationSelect') as HTMLSelectElement;
export const nodeInspectorActions = document.getElementById('nodeInspectorActions')!;
export const nodeInspectorControls = document.getElementById('nodeInspectorControls')!;
export const nodeInspectorRemovalPreview = document.getElementById('nodeInspectorRemovalPreview')!;
export const searchInput = document.getElementById('searchInput') as HTMLInputElement;
export const searchClearBtn = document.getElementById('searchClearBtn') as HTMLButtonElement;
export const searchPreviousBtn = document.getElementById('searchPreviousBtn') as HTMLButtonElement;
export const searchNextBtn = document.getElementById('searchNextBtn') as HTMLButtonElement;
export const searchCounter = document.getElementById('searchCounter')!;
